### ISSUE TITLE
Handle file unacceptable in new version of android

### ISSUE THREAD

**Issue by strazzere** [strazzere/anti-emulator#16]
```
06-17 13:30:18.405 16594 16618 W System.err: java.io.FileNotFoundException: /proc/net/tcp: open failed: EACCES (Permission denied)
06-17 13:30:18.405 16594 16618 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:496)
06-17 13:30:18.405 16594 16618 W System.err:    at java.io.FileInputStream.<init>(FileInputStream.java:159)
06-17 13:30:18.405 16594 16618 W System.err:    at java.io.FileInputStream.<init>(FileInputStream.java:115)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.debugger.FindDebugger.hasAdbInEmulator(FindDebugger.java:70)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.emulator.FindEmulator.hasEmulatorAdb(FindEmulator.java:247)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.MainActivity.isQEmuEnvDetected(MainActivity.java:54)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.MainActivity$1.run(MainActivity.java:30)
06-17 13:30:18.405 16594 16618 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
06-17 13:30:18.405 16594 16618 W System.err:    at libcore.io.Linux.open(Native Method)
06-17 13:30:18.405 16594 16618 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
06-17 13:30:18.405 16594 16618 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
06-17 13:30:18.405 16594 16618 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
06-17 13:30:18.405 16594 16618 W System.err:    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
06-17 13:30:18.405 16594 16618 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:482)
06-17 13:30:18.399 16594 16594 W Thread-2: type=1400 audit(0.0:393745): avc: denied { read } for name="drivers" dev="proc" ino=4026531853 scontext=u:r:untrusted_app:s0:c57,c257,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=0
06-17 13:30:18.405 16594 16618 W System.err:    ... 6 more
06-17 13:30:18.405 16594 16618 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedReader.close()' on a null object reference
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.debugger.FindDebugger.hasAdbInEmulator(FindDebugger.java:103)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.emulator.FindEmulator.hasEmulatorAdb(FindEmulator.java:247)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.MainActivity.isQEmuEnvDetected(MainActivity.java:54)
06-17 13:30:18.405 16594 16618 W System.err:    at diff.strazzere.anti.MainActivity$1.run(MainActivity.java:30)
```

From a pixel 4

**Comment by Mr-Jiang** [comment]
please, look this

https://blog.csdn.net/jspping/article/details/131852570?spm=1001.2014.3001.5501
